"""Add is_read to messages

Revision ID: 8360217d1476
Revises: 2a7a1599e6c3
Create Date: 2025-09-10 09:27:55.294973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8360217d1476'
down_revision: Union[str, Sequence[str], None] = '2a7a1599e6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_posts_search_vector'), table_name='posts', postgresql_using='gin')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('citizen', 'mp', 'admin', 'journalist', name='role'),
               type_=sa.Enum('citizen', 'mp', 'admin', 'journalist', name='role', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'citizen'::role"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('citizen', 'mp', 'admin', 'journalist', name='role', native_enum=False),
               type_=postgresql.ENUM('citizen', 'mp', 'admin', 'journalist', name='role'),
               existing_nullable=False,
               existing_server_default=sa.text("'citizen'::role"))
    op.create_index(op.f('ix_posts_search_vector'), 'posts', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
