"""empty message

Revision ID: 98c3f4f3f512
Revises: b3133f5608bb
Create Date: 2025-08-29 11:24:46.036453

"""
from typing import Sequence, Union
import sqlalchemy_utils 
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c3f4f3f512'
down_revision: Union[str, Sequence[str], None] = 'b3133f5608bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.add_column('posts', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), sa.Computed("to_tsvector('english', title_of_the_post || ' ' || content)", persisted=True), nullable=True))
    op.alter_column('posts', 'title_of_the_post',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), sa.Computed("to_tsvector('english', username || ' ' || email)", persisted=True), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'search_vector')
    op.drop_column('users', 'username')
    op.alter_column('posts', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'title_of_the_post',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('posts', 'search_vector')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
